


						<div id="left-side">
				<a href="#" class="back"><-tagasi</a>
				<h1>pealkiri </h1>
				<p id="subtitle">Koolituse autor:<a href="#">Tiina Tubli</a></p>
				<p id="txt1">Kirjeldus</p>
				<div id="txt2">
					<p><b>Märksõnad:</b> avatus, koolitus</p>
					<p><b>Koolitustegevuse vorm:</b> koolitus</p>
					<p><b>Kuupäevad ja toimumiskohad:</b></p>
					  <p class="indent">23.01 - Tartus</p>
					  <p class="indent">24.01 - Tallinnas</p>
					<p><b>Hind:</b> €500</p>
					<p><b>Taotlus- ja registreerimistähtaeg:</b> 22asdfasdfasgfdgard  jiosigo ioaerh ithiarhgjvshdrthnaierht bjsahntirak thbhait ahsi.01</p>
					<p><b>Viide koolitusele veebis:</b> <a href="#">http://koolistus.ee</a></p>
					<p><b>Grupi suurus:</b> 22</p>
					<p><b>Ettevõtmise ulatus:</b> üleriigiline</p>
					<p><b>Kontaktinfo lisainfo saamiseks:</b></p>
					   <p class="indent">Lisainfot jagab Hunt Kriimsilm</p>
					<p><b>Täiendav teave:</b> kaasa võtta vihik</p>
					<a href="#" class="back_bot"><-tagasi</a>					
				</div>				
			</div>
			<div id="right-side">
				
				
				<div id="pic">
					<div id="white">
						<img src="images/picture.jpg" alt=""/>
					</div>
				</div>
				<a href="#" id="button"></a>
				
				
				<a href="#" id="facebook"></a>
				<a href="#" id="twitter"></a>
				<p>Jaga koolitust sõpradega :)</p>
			</div>