<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <title>Admin</title>
        <meta http-equiv="Content-Type" content="application/xhtml+xml; charset=utf-8" />
        <meta name="author" content="Your Name here" />
        <meta name="keywords" content="" />
        <meta name="description" content="" />
        <link href="<?php echo ROOT_URL?>css/style.css" rel="stylesheet" type="text/css" />
        <!-- Load TinyMCE -->
        <script type="text/javascript" src="http://www.google.com/jsapi"></script>
        <script src="js/jquery-1.4.2.js" ></script>
        <script type="text/javascript">
	        google.load("jquery", "1");
        </script>
        <script type="text/javascript" src="<?php echo ROOT_URL?>js/tinymce/jquery.tinymce.js"></script>
        <script type="text/javascript">
                $().ready(function() {
                        $('textarea.rte').tinymce({
                                // Location of TinyMCE script
                                script_url : '<?php echo ROOT_URL?>js/tinymce/tiny_mce.js',
                                // General options
                                theme : "advanced",
                                plugins : "imagemanager,style,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template,advlist",
                                width : "200px",
                                height : "300px",
                                // Theme options
                                theme_advanced_buttons1 : "bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,fontselect,fontsizeselect,bullist,numlist",
                                theme_advanced_buttons2 : "outdent,indent,blockquote,|,undo,redo,|,link,unlink,cleanup,code,|,insertdate,inserttime,preview,|,forecolor,backcolor,insertimage",
                                theme_advanced_toolbar_location : "top",
                                theme_advanced_toolbar_align : "left",
                                theme_advanced_statusbar_location : "bottom",
                                theme_advanced_resizing : false,
                                theme_advanced_resize_horizontal : false

                        });
                });

        </script>
        <script>
	        $(function() {
		        $( "#datepicker" ).datepicker();
                $( "#datepicker2" ).datepicker();
	        });
	    </script>

        <!-- /TinyMCE -->
    </head>

    <body>
            <?php echo $this->layout()->content ?>
        <div id="r" ><br><br>
            <a href='search'> Search </a><br><br>
            <a href='notice'> Notice </a><br><br>
            <a href='addnewuser'> Add new user </a><br><br>
            <a href='index?page=logout'> Logout </a><br><br>
            <a href='adminedit?page=settings'> Settings </a>
        </div>
    </div>
</div>
<br clear="all"/></div>
            <br clear="all"/></div>
            <div id="footer">
                <div>
                    <div>
                    Copyright &copy; 2010 compname, All Rights Reserved.
                     |  Website by:<a href="http://iguansystems.com">Iguan Systems</a>
                    </div>
                </div>
            </div>
    </body>
</html>
