<?php

//var_dump($this->userInfo);
//exit;

if(count($this->error) > 0){
    foreach($this->error as $error){
        var_Dump($error);
        echo "<br />";
    ?>

<?php } }?>

<table height="350" bordercolor="#d3edfe" border="1" align="center" width="676" style="border-collapse: collapse;">
<tbody><tr>
<td height="19" class="top"><div align="left"><?php echo "Tere, "; ?>! <small>(<a href="index/logout">Logi välja</a>)</small></div></td>
<td colspan="2" class="top"><div align="center"><b><a href="profile">KOOLITUSKALENDRI ARMATUURLAUD</a></b></div></td>
<td class="top"><div align="right">&nbsp;</div></td>
</tr>

<tr>
    <td valign="top" style="width:15%">
       <?php

       echo $this->partial('includes/leftmenu.phtml', array(
             "typeId" => $this->typeId,
             "level" => $this->level
         )); ?>
    </td><td valign="top" colspan="3" style="text-transform: capitalize">
                <table cellspacing="2" cellpadding="2">
                    <thead>
                        <tr>
                            <td>Title</td>
                            <td>Logo</td>
                            <td>deadline</td>
                            <td>Status</td>
                            <td></td>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td colspan="3">New Trainings</td>
                        </tr>
                        <?php
foreach($this->itemsnew as $item) {
    ?>
                        <tr>
                            <td> <a href="admin/eventedit/<?php echo $item['id']?>"><?php echo $item['title']?></a></td>
                            <td> <a href="admin/eventedit/<?php echo $item['id']?>"><img src="img/trainers/<?php echo $item['logo']?>" style="width:100px;" alt="" /></a></td>

                            <td><?php echo date("Y-m-d",strtotime($item['deadline'])); ?></td>
                            <td><?php
                            if($item['published'] == '0'){
                                ?>
                               <a href="admin/approve/<?php echo $item['id']; ?>"> Unapprove</a>
                                <?php
                            }else{
                            ?>
                               Approve
                            <?php }?>
                            </td>
                            <td><a href="admin/remove/trainers/<?php echo $item['id']?>">Remove</a></td>
                        </tr>

                            <?php
}
?>
                        <tr>
                            <td colspan="3">Old Trainings</td>
                        </tr>
                        <?php
foreach($this->itemsold as $item) {
    ?>
                        <tr>
                            <td> <a href="admin/eventedit/<?php echo $item['id']?>"><?php echo $item['title']?></a></td>
                            <td> <a href="admin/eventedit/<?php echo $item['id']?>"><img src="img/trainers/<?php echo $item['logo']?>" style="width:100px;" alt="" /></a></td>

                            <td><?php echo date("Y-m-d",strtotime($item['deadline'])); ?></td>
                            <td><?php
                            if($item['published'] == '0'){
                                ?>
                                <a href="admin/approve/<?php echo $item['id']; ?>"> Unapprove</a>
                                <?php
                            }else{
                            ?>
                               Approve
                            <?php }?>
                            </td>
                            <td><a href="admin/remove/trainers/<?php echo $item['id']?>">Remove</a></td>
                        </tr>

                            <?php
}
?>
                    </tbody>
                </table>
            </td>
        </tr>
    </tbody></table>