<?php

//var_dump($this->userInfo);
//exit;

if(count($this->error) > 0){
    foreach($this->error as $error){
        var_Dump($error);
        echo "<br />";
    ?>

<?php } }?>

<table height="350" bordercolor="#d3edfe" border="1" align="center" width="676" style="border-collapse: collapse;">
<tbody><tr>
<td height="19" class="top"><div align="left"> <small>(<a href="index/logout">Logi välja</a>)</small></div></td>
<td colspan="2" class="top"><div align="center"><b><a href="profile">KOOLITUSKALENDRI ARMATUURLAUD</a></b></div></td>
<td class="top"><div align="right">&nbsp;</div></td>
</tr>

<tr>
    <td valign="top" style="width:15%">

       <?php
       echo $this->partial('includes/leftmenu.phtml', array(
             "typeId" => $this->typeId,
             "level" => $this->level
         )); ?>
    </td><td valign="top" colspan="3" style="text-transform: capitalize">
        <h2><?php echo $this->title; ?></h2>
       <form action="" method="post">
            <input type="hidden" name="id" value="<?php echo $this->item['id']?>" />
            <input type="text" name="name" value="<?php echo $this->item['name']?>"  />
           <br /><br />Mille alla kuulub:<br />
            <select  name='parentId'><option value='0'>None</option>
                 <?php
                        foreach($this->items as $target){
                            
                            echo "<option value='$target[id]' id='$target[id]' ".(($this->item['parentId'] == $target['id'])?'selected':'')." name='parentId'>$target[name]</option>";
                        }
                    ?>

            </select>
<br />            <input type="submit" value="Muuda" />
    </form>


</td>
</tr>
</tbody></table>