<?php

//var_dump($this->userInfo);
//exit;

if(count($this->error) > 0){
    foreach($this->error as $error){
        var_Dump($error);
        echo "<br />";
    ?>

<?php } }?>
<script src="js/colorpicker.js" type="text/javascript"></script>
<script type="text/javascript">
    $(document).ready(function(){
        $('#colorpickerField1').ColorPicker({
                onSubmit: function(hsb, hex, rgb, el) {
                        $(el).val(hex);
                        $(el).ColorPickerHide();
                },
                onBeforeShow: function () {
                        $(this).ColorPickerSetColor(this.value);
                        $('.colorDiv').css('background','#'+this.value);
                },

                onChange: function (hsb, hex, rgb){
             
                    $('.colorDiv').css('background','#'+hex);
                    $("#colorpickerField1").val(hex);
                }

        })
        .bind('keyup', function(){
                $(this).ColorPickerSetColor(this.value);
                $('.colorDiv').css('background','#'+this.value);

        });

    });
</script>
<table height="350" bordercolor="#d3edfe" border="1" align="center" width="676" style="border-collapse: collapse;">
<tbody><tr>
<td height="19" class="top"><div align="left"> <small>(<a href="index/logout">Logi välja</a>)</small></div></td>
<td colspan="2" class="top"><div align="center"><b><a href="profile">KOOLITUSKALENDRI ARMATUURLAUD</a></b></div></td>
<td class="top"><div align="right">&nbsp;</div></td>
</tr>

<tr>
    <td valign="top" style="width:15%">

       <?php
       echo $this->partial('includes/leftmenu.phtml', array(
             "typeId" => $this->typeId,
             "level" => $this->level
         )); ?>
    </td><td valign="top" colspan="3" style="text-transform: capitalize">
        <h2><?php echo $this->title; ?></h2>
       <form action="" method="post">
            <input type="hidden" name="id" value="<?php echo $this->item['id']?>" />
            <input type="text" name="name" value="<?php echo $this->item['name']?>"  />
            <div style="width:30px; height: 30px; background: transparent" class="colorDiv" "></div>

           <input type="text" id="colorpickerField1"  name="color" value="<?php echo $this->item['color']?>"/> <br />
                       <br />
            <input type="submit" value="Muuda" />
    </form>
        

</td>
</tr>
</tbody></table>